### ISSUE TITLE
Pass thread id to task ?

### ISSUE THREAD

**Issue by boxerab** [zserik/ThreadPool#2]
This is a very nice up to date version, thanks for making this available.
In my use case, I would like the task to access a structure based on the
thread id - is is possible to pass this to the task ?

**Comment by boxerab** [comment]
never mind, figured it out :)

**Comment by boxerab** [comment]
nope, still can't figure it out

**Comment by zserik** [comment]
Doesn't [`std::this_thread::get_id()`](https://en.cppreference.com/w/cpp/thread/get_id) work?

**Comment by boxerab** [comment]
Thanks! I was hoping to get the thread number from the pool, i.e. 0,1,..... num_threads.
But, I guess I can use the thread id for my purpose : access per-thread data.
